#!/bin/bash
set -e

RELEASE=1.7
JAR_NAME="google-java-format-${RELEASE}-all-deps.jar"
RELEASES_URL=https://github.com/google/google-java-format/releases/download
JAR_URL="${RELEASES_URL}/google-java-format-${RELEASE}/${JAR_NAME}"

JAR_FILE=".git/hooks/$JAR_NAME"
JAR_PGP_ASC_FILE="${JAR_FILE}.asc"

if [[ ! -f "$JAR_FILE" ]]
then
    curl -L "$JAR_URL" -o "$JAR_FILE"
    cat >"$JAR_PGP_ASC_FILE" <<EOF
EOF
fi

changed_java_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*java$" || true)
if [[ -n "$changed_java_files" ]]
then
    if ! java -jar "$JAR_FILE" --replace --set-exit-if-changed $changed_java_files
    then
        echo "Commit was aborted due to reformatting and unused imports. Commit again before making any changes!!!! Auto Code Reviewer :) " >&2
        exit 1
    fi
else
    echo "No Java files changes found."
fi